services:
  - type: web
    name: paysync-backend
    env: python
    rootDir: paysync-backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run_migrations.py && gunicorn wsgi:app
    plan: free
    envVars:
      - fromGroup: paysync-env
